services:
  MediaWiki:
    container_name: wiki
    image: mediawiki
    restart: always
    ports: 
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
     # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  database:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: WikiP@ssw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - dbvolume:/var/lib/mariadb
volumes:
  dbvolume:
      external: true
  images:
