version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: WikiP@ssw0rd
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mediawiki_network

  wiki:
    image: mediawiki:latest
    container_name: wiki
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: mariadb
      MEDIAWIKI_DB_NAME: mediawiki
      MEDIAWIKI_DB_USER: wiki
      MEDIAWIKI_DB_PASSWORD: WikiP@ssw0rd
    volumes:
      - ~/LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - mediawiki_network

volumes:
  mariadb_data:
    driver: local

networks:
  mediawiki_network:
    driver: bridge
